### ISSUE TITLE
teamwork of NTP over LTE and RTC

### ISSUE THREAD

**Issue by lampep** [Nature40/BatRackOS#2]
Find a way of updating the time over NTP and update the RTC if a remote connection is available and otherwise use the RTC as source of the current time

**Comment by jonashoechst** [comment]
In principal there are 4 time sources we can use: 
- [fake-hwclock](https://packages.debian.org/en/sid/fake-hwclock) (writing time to disk periodically, reading on boot), very inaccurate
- Real-Time Clock, failing and resetting sometimes
- NTP; only available if internet access is available
- [GPS through SDR](https://gnss-sdr.org), untested, long startup phase, high reliabilty

Our targets are:
- high versatility (with / without LTE / RTC)
- accurate timings, since wall clock is required for ecology observation.

In principal combinations could work:
 - RTC + fake-hwclock
 - NTP
 - GPS

Whoever gets an accurate time first, sets the system time and activates the systems time sync target.

**Comment by jonashoechst** [comment]
Combination of hwclock and systemd-timesyncd is not trivial, especially, if `systemd-time-wait-sync.service` is enabled. Therefore we created a simple service called on boot, which reads hwclock, sets the time and disables time-wait-sync. 

For stations without NTP time synchronization, the station should be booted, the hwclock be set and bespoken hwclock service be activated.

https://github.com/Nature40/BatRackOS/blob/9eb60409907ab6515d26bbe30c3a3116082b41b6/etc/systemd/system/hwclock.service#L5-L8
